version: '3.8'

services:
  db:
    image: postgres:15
    container_name: guestbook-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - guestbookdata:/var/lib/postgresql/data

  guestbook-practice-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guestbook-practice-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_BASE_URL=${AWS_S3_BASE_URL}
    restart: always

volumes:
  guestbookdata: